### ISSUE TITLE
关于此核心的conf

### ISSUE THREAD

**Issue by Wshape1** [TSRTW/T-STAR#1]
<h1>我需要一个能够配合此核心的conf来运行Multicraft。希望作者有空写个conf.</h1> 
![qq 20170207142239](https://cloud.githubusercontent.com/assets/17956037/22680104/5557751c-ed41-11e6-860d-c539d4f2d808.png)

**Comment by lightda104530** [comment]
會抽時間去

**Comment by lightda104530** [comment]
個人測試沒問題
